# Generated by Django 5.1.4 on 2025-01-07 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ap_id', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=50, null=True)),
                ('doc_id', models.CharField(max_length=50, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('disease', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=1500)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('mid_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=13)),
                ('payment_intent_id', models.CharField(max_length=100, null=True)),
                ('payment_status', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(max_length=20)),
                ('doc_name', models.CharField(max_length=250)),
                ('doc_email', models.EmailField(max_length=254)),
                ('profile', models.CharField(max_length=1500)),
                ('experiance', models.CharField(max_length=250)),
                ('hospital', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=13)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MedicalCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('condition', models.CharField(max_length=100)),
                ('severity', models.CharField(max_length=520)),
                ('medication', models.CharField(max_length=100)),
                ('doctor', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dosage_options', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('side_effects', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=1500)),
                ('news', models.CharField(max_length=1500)),
                ('date', models.DateField(auto_now=True)),
                ('doctor', models.CharField(max_length=150)),
                ('image', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('medical_condition', models.CharField(max_length=500)),
                ('date', models.DateField(auto_now=True)),
                ('remarks', models.TextField()),
                ('outcome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=450)),
                ('profile', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='MedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ap_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hospitalcore.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=100)),
                ('times_per_day', models.IntegerField()),
                ('routine', models.CharField(max_length=10)),
                ('medicines', models.ManyToManyField(to='hospitalcore.medicine')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalcore.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=1500)),
                ('severity', models.CharField(max_length=1500)),
                ('medication', models.CharField(max_length=1500)),
                ('date', models.DateField(auto_now=True)),
                ('status', models.CharField(max_length=150)),
                ('remark', models.CharField(max_length=200)),
                ('outcome', models.CharField(max_length=200)),
                ('doctor', models.ManyToManyField(to='hospitalcore.doctormodel')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hospitalcore.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='HeathStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressure', models.CharField(max_length=100)),
                ('sugar', models.CharField(max_length=100)),
                ('cholestrol', models.CharField(max_length=100)),
                ('pre_expl', models.CharField(max_length=300)),
                ('sug_expl', models.CharField(max_length=300)),
                ('chol_expl', models.CharField(max_length=300)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hospitalcore.usermodel')),
            ],
        ),
    ]
