# Generated by Django 5.1.4 on 2025-01-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalcore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('services', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('contact', models.CharField(max_length=25)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
