# Generated by Django 5.0.7 on 2024-12-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalcore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
        migrations.AddField(
            model_name='appointment',
            name='doc_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
