# Generated by Django 5.1.4 on 2025-01-11 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalcore', '0002_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedAppointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ap_id', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=50, null=True)),
                ('doc_id', models.CharField(max_length=50, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('disease', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=1500)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('mid_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=13)),
                ('payment_intent_id', models.CharField(max_length=100, null=True)),
                ('payment_status', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
