from django.urls import path
from . import views

urlpatterns = [
    path("create-user/", views.UserList.as_view(), name="create-user"),
    path("list-user", views.ListUsers.as_view(), name="list-user"),
    path("user/<int:user_id>", views.ListSingleUser.as_view(), name="single"),
    path("update-user/<int:pk>/", views.UserDetail.as_view(), name="user-detail"),
    path("delete-user/<int:pk>/", views.DeleteUser.as_view(), name="delete-user"),
    path('login-user/', views.LoginUser.as_view(), name='login-user'),   
    path("create-doctor", views.DoctorList.as_view(), name="create-doctor"),
    path("list-doctor", views.ListDoctor.as_view(), name="list-doctor"),
    path("doctor/<int:pk>", views.DoctorDetail.as_view(), name="doctor-detail"),
    path("create-med-history", views.MedHistoryList.as_view(), name="create-med-history"),
    path("med-history/<int:pk>", views.MedHistoryDetail.as_view(), name="med-history-detail"),
    path("create-heath-status", views.HeathStatusList.as_view(), name="create-heath-status"),
    path("heath-status/<int:pk>", views.HeathStatusDetail.as_view(), name="heath-status-detail"),
    path("create-med-news", views.MedNewsList.as_view(), name="create-med-news"),
    path("list-mednews/", views.ListMedNews.as_view(), name="med-news-detail"),
    path("create-appointment", views.CreateAppointment.as_view(), name="list-med-news"),
    path("list-appointment", views.ListAppointment.as_view(), name="create-appointment"),
    path("remove-appointment/<int:pk>", views.RemoveAppointment.as_view(), name="remove-appointment"),
    path("create-treatment-history", views.CreateTreatment.as_view(), name="create-treatment"),
    path("list-treatment-history", views.ListTreatment.as_view(), name="list-treatment"),
    path("create-med-condition", views.CreateMedicalCondition.as_view(), name="create-med-condition"),
    path("list-med-condition", views.ListMedicalCondition.as_view(), name="list-med-condition"),
    path('create-payment-intent/', views.CreatePaymentIntentView.as_view()),
    path('appointments/', views.AppointmentView.as_view()),
    path('pay-appointment/', views.CreateAppointmentView.as_view(),name='pay-appointment'),
    path("create-medicine", views.CreateMedicine.as_view(), name="create-medicine"),
    path("list-medicine", views.ListMedicine.as_view(), name="list-medicine"),
    path("create-prescription", views.CreatePrescription.as_view(), name="create-prescription"),
    path("list-prescription", views.ListPrescription.as_view(), name="list-prescription"),
    path("create-hospital", views.CreateHospital.as_view(), name="create-hospital"),
    path("list-hospital", views.ListHospital.as_view(), name="list-hospital"),
    path("update-hospital/<int:pk>", views.UpdateHospital.as_view(), name="update-hospital"),
    path("delete-hospital/<int:pk>", views.DeleteHospital.as_view(), name="delete-hospital"),
    path("update-appointment/<int:pk>/", views.UpdateAppointment.as_view(), name="update-appointment"),
    path("delete-appointment/<int:pk>/", views.DeleteAppointment.as_view(), name="delete-appointment"),
    path("update-doctor/<int:pk>/", views.UpdateDoctor.as_view(), name="update-doctor"),
    path("delete-doctor/<int:pk>/", views.DeleteDoctor.as_view(), name="delete-doctor"),
    path("approved-appointment/", views.ApprovedAppointment.as_view(), name="approve-appointment"),
    path("list-approved-appointment/", views.ListApprovedAppointment.as_view(), name="list-approved-appointment"),
    path("create-notification/", views.CreateNotification.as_view(), name="create-notification"),
    path("list-notification/", views.ListNotification.as_view(), name="list-notification"),
    path("update-notification/<int:pk>/", views.UpdateNotification.as_view(), name="update-notification"),
    path("recieve-data", views.RecieveData.as_view(), name="recieve-data"),
]